-- FRVGMXNT GUI2LUA CONVERTER 1.2. Like pls!
local All = {
	All = Instance.new("ScreenGui"),
	Jump_HeightGUI = Instance.new("ScreenGui"),
	Dragger = Instance.new("Frame"),
	TransMainFrame = Instance.new("Frame"),
	UICorner = Instance.new("UICorner"),
	MainFrame = Instance.new("Frame"),
	UICorner_2 = Instance.new("UICorner"),
	TextBox = Instance.new("TextBox"),
	UICorner_3 = Instance.new("UICorner"),
	TitleFrame = Instance.new("Frame"),
	UICorner_4 = Instance.new("UICorner"),
	TextLabel = Instance.new("TextLabel"),
	Fly_SpeedGUI = Instance.new("ScreenGui"),
	Dragger_2 = Instance.new("Frame"),
	TransMainFrame_2 = Instance.new("Frame"),
	UICorner_5 = Instance.new("UICorner"),
	MainFrame_2 = Instance.new("Frame"),
	UICorner_6 = Instance.new("UICorner"),
	TextBox_2 = Instance.new("TextBox"),
	UICorner_7 = Instance.new("UICorner"),
	TitleFrame_2 = Instance.new("Frame"),
	UICorner_8 = Instance.new("UICorner"),
	TextLabel_2 = Instance.new("TextLabel"),
	NullGUI = Instance.new("ScreenGui"),
	Dragger_3 = Instance.new("Frame"),
	TransMainFrame_3 = Instance.new("Frame"),
	UICorner_9 = Instance.new("UICorner"),
	TitleFrame_3 = Instance.new("Frame"),
	UICorner_10 = Instance.new("UICorner"),
	TextLabel_3 = Instance.new("TextLabel"),
	MainFrame_3 = Instance.new("Frame"),
	UICorner_11 = Instance.new("UICorner"),
	ScrollingFrame = Instance.new("ScrollingFrame"),
	ESP = Instance.new("TextButton"),
	UICorner_12 = Instance.new("UICorner"),
	UIListLayout = Instance.new("UIListLayout"),
	FLY = Instance.new("TextButton"),
	UICorner_13 = Instance.new("UICorner"),
	SERVER = Instance.new("TextButton"),
	UICorner_14 = Instance.new("UICorner"),
	NOCLIP = Instance.new("TextButton"),
	UICorner_15 = Instance.new("UICorner"),
	WALKSPEED = Instance.new("TextButton"),
	UICorner_16 = Instance.new("UICorner"),
	JUMPHEIGHT = Instance.new("TextButton"),
	UICorner_17 = Instance.new("UICorner"),
	TOOL = Instance.new("TextButton"),
	UICorner_18 = Instance.new("UICorner"),
	Noclip_SpeedGUI = Instance.new("ScreenGui"),
	Dragger_4 = Instance.new("Frame"),
	TransMainFrame_4 = Instance.new("Frame"),
	UICorner_19 = Instance.new("UICorner"),
	MainFrame_4 = Instance.new("Frame"),
	UICorner_20 = Instance.new("UICorner"),
	TextBox_3 = Instance.new("TextBox"),
	UICorner_21 = Instance.new("UICorner"),
	TitleFrame_4 = Instance.new("Frame"),
	UICorner_22 = Instance.new("UICorner"),
	TextLabel_4 = Instance.new("TextLabel"),
	Walk_SpeedGUI = Instance.new("ScreenGui"),
	Dragger_5 = Instance.new("Frame"),
	TransMainFrame_5 = Instance.new("Frame"),
	UICorner_23 = Instance.new("UICorner"),
	MainFrame_5 = Instance.new("Frame"),
	UICorner_24 = Instance.new("UICorner"),
	TextBox_4 = Instance.new("TextBox"),
	UICorner_25 = Instance.new("UICorner"),
	TitleFrame_5 = Instance.new("Frame"),
	UICorner_26 = Instance.new("UICorner"),
	TextLabel_5 = Instance.new("TextLabel"),
	ToolGUI = Instance.new("ScreenGui"),
	Dragger_6 = Instance.new("Frame"),
	TransMainFrame_6 = Instance.new("Frame"),
	UICorner_27 = Instance.new("UICorner"),
	MainFrame_6 = Instance.new("Frame"),
	UICorner_28 = Instance.new("UICorner"),
	TextBox_5 = Instance.new("TextBox"),
	UICorner_29 = Instance.new("UICorner"),
	TitleFrame_6 = Instance.new("Frame"),
	UICorner_30 = Instance.new("UICorner"),
	TextLabel_6 = Instance.new("TextLabel"),
}

All.All.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
All.Jump_HeightGUI.Parent = All.All
All.Dragger.Parent = All.Jump_HeightGUI
All.TransMainFrame.Parent = All.Dragger
All.UICorner.Parent = All.TransMainFrame
All.MainFrame.Parent = All.TransMainFrame
All.UICorner_2.Parent = All.MainFrame
All.TextBox.Parent = All.MainFrame
All.UICorner_3.Parent = All.TextBox
All.TitleFrame.Parent = All.TransMainFrame
All.UICorner_4.Parent = All.TitleFrame
All.TextLabel.Parent = All.TitleFrame
All.Fly_SpeedGUI.Parent = All.All
All.Dragger_2.Parent = All.Fly_SpeedGUI
All.TransMainFrame_2.Parent = All.Dragger_2
All.UICorner_5.Parent = All.TransMainFrame_2
All.MainFrame_2.Parent = All.TransMainFrame_2
All.UICorner_6.Parent = All.MainFrame_2
All.TextBox_2.Parent = All.MainFrame_2
All.UICorner_7.Parent = All.TextBox_2
All.TitleFrame_2.Parent = All.TransMainFrame_2
All.UICorner_8.Parent = All.TitleFrame_2
All.TextLabel_2.Parent = All.TitleFrame_2
All.NullGUI.Parent = All.All
All.Dragger_3.Parent = All.NullGUI
All.TransMainFrame_3.Parent = All.Dragger_3
All.UICorner_9.Parent = All.TransMainFrame_3
All.TitleFrame_3.Parent = All.TransMainFrame_3
All.UICorner_10.Parent = All.TitleFrame_3
All.TextLabel_3.Parent = All.TitleFrame_3
All.MainFrame_3.Parent = All.TransMainFrame_3
All.UICorner_11.Parent = All.MainFrame_3
All.ScrollingFrame.Parent = All.MainFrame_3
All.ESP.Parent = All.ScrollingFrame
All.UICorner_12.Parent = All.ESP
All.UIListLayout.Parent = All.ScrollingFrame
All.FLY.Parent = All.ScrollingFrame
All.UICorner_13.Parent = All.FLY
All.SERVER.Parent = All.ScrollingFrame
All.UICorner_14.Parent = All.SERVER
All.NOCLIP.Parent = All.ScrollingFrame
All.UICorner_15.Parent = All.NOCLIP
All.WALKSPEED.Parent = All.ScrollingFrame
All.UICorner_16.Parent = All.WALKSPEED
All.JUMPHEIGHT.Parent = All.ScrollingFrame
All.UICorner_17.Parent = All.JUMPHEIGHT
All.TOOL.Parent = All.ScrollingFrame
All.UICorner_18.Parent = All.TOOL
All.Noclip_SpeedGUI.Parent = All.All
All.Dragger_4.Parent = All.Noclip_SpeedGUI
All.TransMainFrame_4.Parent = All.Dragger_4
All.UICorner_19.Parent = All.TransMainFrame_4
All.MainFrame_4.Parent = All.TransMainFrame_4
All.UICorner_20.Parent = All.MainFrame_4
All.TextBox_3.Parent = All.MainFrame_4
All.UICorner_21.Parent = All.TextBox_3
All.TitleFrame_4.Parent = All.TransMainFrame_4
All.UICorner_22.Parent = All.TitleFrame_4
All.TextLabel_4.Parent = All.TitleFrame_4
All.Walk_SpeedGUI.Parent = All.All
All.Dragger_5.Parent = All.Walk_SpeedGUI
All.TransMainFrame_5.Parent = All.Dragger_5
All.UICorner_23.Parent = All.TransMainFrame_5
All.MainFrame_5.Parent = All.TransMainFrame_5
All.UICorner_24.Parent = All.MainFrame_5
All.TextBox_4.Parent = All.MainFrame_5
All.UICorner_25.Parent = All.TextBox_4
All.TitleFrame_5.Parent = All.TransMainFrame_5
All.UICorner_26.Parent = All.TitleFrame_5
All.TextLabel_5.Parent = All.TitleFrame_5
All.ToolGUI.Parent = All.All
All.Dragger_6.Parent = All.ToolGUI
All.TransMainFrame_6.Parent = All.Dragger_6
All.UICorner_27.Parent = All.TransMainFrame_6
All.MainFrame_6.Parent = All.TransMainFrame_6
All.UICorner_28.Parent = All.MainFrame_6
All.TextBox_5.Parent = All.MainFrame_6
All.UICorner_29.Parent = All.TextBox_5
All.TitleFrame_6.Parent = All.TransMainFrame_6
All.UICorner_30.Parent = All.TitleFrame_6
All.TextLabel_6.Parent = All.TitleFrame_6

All.All.Name = "All"
All.All.ResetOnSpawn = true
All.All.IgnoreGuiInset = false
All.All.DisplayOrder = 0

All.Jump_HeightGUI.Name = "Jump_HeightGUI"
All.Jump_HeightGUI.ResetOnSpawn = false
All.Jump_HeightGUI.IgnoreGuiInset = true
All.Jump_HeightGUI.DisplayOrder = 0

All.Dragger.Name = "Dragger"
All.Dragger.ZIndex = 1
All.Dragger.Position = UDim2.new(0.294513255, 0, 0.137446374, 0)
All.Dragger.Size = UDim2.new(0.323998362, 0, 0.0558748394, 0)
All.Dragger.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.Dragger.BackgroundTransparency = 1
All.Dragger.Visible = false
All.Dragger.AnchorPoint = Vector2.new(0, 0)
All.Dragger.ClipsDescendants = false
All.Dragger.BorderSizePixel = 0
All.Dragger.Draggable = true

All.TransMainFrame.Name = "TransMainFrame"
All.TransMainFrame.ZIndex = 0
All.TransMainFrame.Position = UDim2.new(0.000111095535, 0, -0.00602852972, 0)
All.TransMainFrame.Size = UDim2.new(1, 0, 4.19999981, 0)
All.TransMainFrame.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TransMainFrame.BackgroundTransparency = 0.30000001192092896
All.TransMainFrame.Visible = true
All.TransMainFrame.AnchorPoint = Vector2.new(0, 0)
All.TransMainFrame.ClipsDescendants = false
All.TransMainFrame.BorderSizePixel = 0

All.UICorner.Name = "UICorner"
All.UICorner.CornerRadius = UDim.new(0, 8)

All.MainFrame.Name = "MainFrame"
All.MainFrame.ZIndex = 1
All.MainFrame.Position = UDim2.new(0.00653942581, 0, 0.27871412, 0)
All.MainFrame.Size = UDim2.new(0.984227121, 0, 0.700680256, 0)
All.MainFrame.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.MainFrame.BackgroundTransparency = 0
All.MainFrame.Visible = true
All.MainFrame.AnchorPoint = Vector2.new(0, 0)
All.MainFrame.ClipsDescendants = false
All.MainFrame.BorderSizePixel = 0

All.UICorner_2.Name = "UICorner"
All.UICorner_2.CornerRadius = UDim.new(0, 8)

All.TextBox.Name = "TextBox"
All.TextBox.ZIndex = 1
All.TextBox.Position = UDim2.new(0.179487184, 0, 0.261682242, 0)
All.TextBox.Size = UDim2.new(0.641025662, 0, 0.485436887, 0)
All.TextBox.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextBox.BackgroundTransparency = 0
All.TextBox.Text = "7.2"
All.TextBox.TextScaled = true
All.TextBox.TextSize = 14
All.TextBox.Font = Enum.Font.Highway
All.TextBox.TextColor3 = Color3.fromRGB(138,138,138)
All.TextBox.TextStrokeColor3 = Color3.fromRGB(22,24,26)
All.TextBox.TextStrokeTransparency = 1
All.TextBox.TextWrapped = true
All.TextBox.TextXAlignment = Enum.TextXAlignment.Center
All.TextBox.TextYAlignment = Enum.TextYAlignment.Center
All.TextBox.TextTransparency = 0
All.TextBox.ClearTextOnFocus = false
All.TextBox.MultiLine = false
All.TextBox.Visible = true
All.TextBox.AnchorPoint = Vector2.new(0, 0)
All.TextBox.ClipsDescendants = false

All.UICorner_3.Name = "UICorner"
All.UICorner_3.CornerRadius = UDim.new(0, 8)

All.TitleFrame.Name = "TitleFrame"
All.TitleFrame.ZIndex = 1
All.TitleFrame.Position = UDim2.new(0.00653923349, 0, 0.0119033083, 0)
All.TitleFrame.Size = UDim2.new(0.984227121, 0, 0.238095239, 0)
All.TitleFrame.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TitleFrame.BackgroundTransparency = 0
All.TitleFrame.Visible = true
All.TitleFrame.AnchorPoint = Vector2.new(0, 0)
All.TitleFrame.ClipsDescendants = false
All.TitleFrame.BorderSizePixel = 0

All.UICorner_4.Name = "UICorner"
All.UICorner_4.CornerRadius = UDim.new(0, 8)

All.TextLabel.Name = "TextLabel"
All.TextLabel.ZIndex = 1
All.TextLabel.Position = UDim2.new(0.0279824678, 0, -0.0712120757, 0)
All.TextLabel.Size = UDim2.new(0.458333343, 0, 0.971428573, 0)
All.TextLabel.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextLabel.BackgroundTransparency = 1
All.TextLabel.Text = "JumpHeight"
All.TextLabel.TextScaled = true
All.TextLabel.TextSize = 14
All.TextLabel.Font = Enum.Font.Highway
All.TextLabel.TextColor3 = Color3.fromRGB(40,43,46)
All.TextLabel.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.TextLabel.TextStrokeTransparency = 1
All.TextLabel.TextWrapped = true
All.TextLabel.TextXAlignment = Enum.TextXAlignment.Left
All.TextLabel.TextYAlignment = Enum.TextYAlignment.Center
All.TextLabel.TextTransparency = 0
All.TextLabel.Visible = true
All.TextLabel.AnchorPoint = Vector2.new(0, 0)
All.TextLabel.ClipsDescendants = false

All.Fly_SpeedGUI.Name = "Fly_SpeedGUI"
All.Fly_SpeedGUI.ResetOnSpawn = false
All.Fly_SpeedGUI.IgnoreGuiInset = true
All.Fly_SpeedGUI.DisplayOrder = 0

All.Dragger_2.Name = "Dragger"
All.Dragger_2.ZIndex = 1
All.Dragger_2.Position = UDim2.new(0.294513255, 0, 0.137446374, 0)
All.Dragger_2.Size = UDim2.new(0.323998362, 0, 0.0558748394, 0)
All.Dragger_2.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.Dragger_2.BackgroundTransparency = 1
All.Dragger_2.Visible = false
All.Dragger_2.AnchorPoint = Vector2.new(0, 0)
All.Dragger_2.ClipsDescendants = false
All.Dragger_2.BorderSizePixel = 0
All.Dragger_2.Draggable = true


All.TransMainFrame_2.Name = "TransMainFrame"
All.TransMainFrame_2.ZIndex = 0
All.TransMainFrame_2.Position = UDim2.new(0.000111095535, 0, -0.00602852972, 0)
All.TransMainFrame_2.Size = UDim2.new(1, 0, 4.19999981, 0)
All.TransMainFrame_2.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TransMainFrame_2.BackgroundTransparency = 0.30000001192092896
All.TransMainFrame_2.Visible = true
All.TransMainFrame_2.AnchorPoint = Vector2.new(0, 0)
All.TransMainFrame_2.ClipsDescendants = false
All.TransMainFrame_2.BorderSizePixel = 0

All.UICorner_5.Name = "UICorner"
All.UICorner_5.CornerRadius = UDim.new(0, 8)

All.MainFrame_2.Name = "MainFrame"
All.MainFrame_2.ZIndex = 1
All.MainFrame_2.Position = UDim2.new(0.00653942581, 0, 0.27871412, 0)
All.MainFrame_2.Size = UDim2.new(0.984227121, 0, 0.700680256, 0)
All.MainFrame_2.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.MainFrame_2.BackgroundTransparency = 0
All.MainFrame_2.Visible = true
All.MainFrame_2.AnchorPoint = Vector2.new(0, 0)
All.MainFrame_2.ClipsDescendants = false
All.MainFrame_2.BorderSizePixel = 0

All.UICorner_6.Name = "UICorner"
All.UICorner_6.CornerRadius = UDim.new(0, 8)

All.TextBox_2.Name = "TextBox"
All.TextBox_2.ZIndex = 1
All.TextBox_2.Position = UDim2.new(0.179487184, 0, 0.261682242, 0)
All.TextBox_2.Size = UDim2.new(0.641025662, 0, 0.485436887, 0)
All.TextBox_2.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextBox_2.BackgroundTransparency = 0
All.TextBox_2.Text = "100"
All.TextBox_2.TextScaled = true
All.TextBox_2.TextSize = 14
All.TextBox_2.Font = Enum.Font.Highway
All.TextBox_2.TextColor3 = Color3.fromRGB(138,138,138)
All.TextBox_2.TextStrokeColor3 = Color3.fromRGB(22,24,26)
All.TextBox_2.TextStrokeTransparency = 1
All.TextBox_2.TextWrapped = true
All.TextBox_2.TextXAlignment = Enum.TextXAlignment.Center
All.TextBox_2.TextYAlignment = Enum.TextYAlignment.Center
All.TextBox_2.TextTransparency = 0
All.TextBox_2.ClearTextOnFocus = false
All.TextBox_2.MultiLine = false
All.TextBox_2.Visible = true
All.TextBox_2.AnchorPoint = Vector2.new(0, 0)
All.TextBox_2.ClipsDescendants = false

All.UICorner_7.Name = "UICorner"
All.UICorner_7.CornerRadius = UDim.new(0, 8)

All.TitleFrame_2.Name = "TitleFrame"
All.TitleFrame_2.ZIndex = 1
All.TitleFrame_2.Position = UDim2.new(0.00653923349, 0, 0.0119033083, 0)
All.TitleFrame_2.Size = UDim2.new(0.984227121, 0, 0.238095239, 0)
All.TitleFrame_2.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TitleFrame_2.BackgroundTransparency = 0
All.TitleFrame_2.Visible = true
All.TitleFrame_2.AnchorPoint = Vector2.new(0, 0)
All.TitleFrame_2.ClipsDescendants = false
All.TitleFrame_2.BorderSizePixel = 0

All.UICorner_8.Name = "UICorner"
All.UICorner_8.CornerRadius = UDim.new(0, 8)

All.TextLabel_2.Name = "TextLabel"
All.TextLabel_2.ZIndex = 1
All.TextLabel_2.Position = UDim2.new(0.0279824678, 0, -0.0712120757, 0)
All.TextLabel_2.Size = UDim2.new(0.458333343, 0, 0.971428573, 0)
All.TextLabel_2.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextLabel_2.BackgroundTransparency = 1
All.TextLabel_2.Text = "Fly - Speed"
All.TextLabel_2.TextScaled = true
All.TextLabel_2.TextSize = 14
All.TextLabel_2.Font = Enum.Font.Highway
All.TextLabel_2.TextColor3 = Color3.fromRGB(40,43,46)
All.TextLabel_2.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.TextLabel_2.TextStrokeTransparency = 1
All.TextLabel_2.TextWrapped = true
All.TextLabel_2.TextXAlignment = Enum.TextXAlignment.Left
All.TextLabel_2.TextYAlignment = Enum.TextYAlignment.Center
All.TextLabel_2.TextTransparency = 0
All.TextLabel_2.Visible = true
All.TextLabel_2.AnchorPoint = Vector2.new(0, 0)
All.TextLabel_2.ClipsDescendants = false

All.NullGUI.Name = "NullGUI"
All.NullGUI.ResetOnSpawn = false
All.NullGUI.IgnoreGuiInset = true
All.NullGUI.DisplayOrder = 0

All.Dragger_3.Name = "Dragger"
All.Dragger_3.ZIndex = 1
All.Dragger_3.Position = UDim2.new(0.218483731, 0, 0.217652783, 0)
All.Dragger_3.Size = UDim2.new(0.507972181, 0, 0.100574709, 0)
All.Dragger_3.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.Dragger_3.BackgroundTransparency = 1
All.Dragger_3.Visible = true
All.Dragger_3.AnchorPoint = Vector2.new(0, 0)
All.Dragger_3.ClipsDescendants = false
All.Dragger_3.BorderSizePixel = 0
All.Dragger_3.Draggable = true


All.TransMainFrame_3.Name = "TransMainFrame"
All.TransMainFrame_3.ZIndex = 0
All.TransMainFrame_3.Position = UDim2.new(-0.00140509813, 0, -0.00526888389, 0)
All.TransMainFrame_3.Size = UDim2.new(1, 0, 4.17460299, 0)
All.TransMainFrame_3.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TransMainFrame_3.BackgroundTransparency = 0.30000001192092896
All.TransMainFrame_3.Visible = true
All.TransMainFrame_3.AnchorPoint = Vector2.new(0, 0)
All.TransMainFrame_3.ClipsDescendants = false
All.TransMainFrame_3.BorderSizePixel = 0

All.UICorner_9.Name = "UICorner"
All.UICorner_9.CornerRadius = UDim.new(0, 8)

All.TitleFrame_3.Name = "TitleFrame"
All.TitleFrame_3.ZIndex = 1
All.TitleFrame_3.Position = UDim2.new(0.00653929682, 0, 0.0119004631, 0)
All.TitleFrame_3.Size = UDim2.new(0.985915482, 0, 0.228136867, 0)
All.TitleFrame_3.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TitleFrame_3.BackgroundTransparency = 0
All.TitleFrame_3.Visible = true
All.TitleFrame_3.AnchorPoint = Vector2.new(0, 0)
All.TitleFrame_3.ClipsDescendants = false
All.TitleFrame_3.BorderSizePixel = 0

All.UICorner_10.Name = "UICorner"
All.UICorner_10.CornerRadius = UDim.new(0, 8)

All.TextLabel_3.Name = "TextLabel"
All.TextLabel_3.ZIndex = 1
All.TextLabel_3.Position = UDim2.new(0.0183673464, 0, 0.0500000007, 0)
All.TextLabel_3.Size = UDim2.new(0.334693879, 0, 0.716666698, 0)
All.TextLabel_3.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextLabel_3.BackgroundTransparency = 1
All.TextLabel_3.Text = "NullScript"
All.TextLabel_3.TextScaled = true
All.TextLabel_3.TextSize = 14
All.TextLabel_3.Font = Enum.Font.Highway
All.TextLabel_3.TextColor3 = Color3.fromRGB(40,43,46)
All.TextLabel_3.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.TextLabel_3.TextStrokeTransparency = 1
All.TextLabel_3.TextWrapped = true
All.TextLabel_3.TextXAlignment = Enum.TextXAlignment.Left
All.TextLabel_3.TextYAlignment = Enum.TextYAlignment.Center
All.TextLabel_3.TextTransparency = 0
All.TextLabel_3.Visible = true
All.TextLabel_3.AnchorPoint = Vector2.new(0, 0)
All.TextLabel_3.ClipsDescendants = false

All.MainFrame_3.Name = "MainFrame"
All.MainFrame_3.ZIndex = 1
All.MainFrame_3.Position = UDim2.new(0.00653923536, 0, 0.251444191, 0)
All.MainFrame_3.Size = UDim2.new(0.985915482, 0, 0.733840287, 0)
All.MainFrame_3.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.MainFrame_3.BackgroundTransparency = 0
All.MainFrame_3.Visible = true
All.MainFrame_3.AnchorPoint = Vector2.new(0, 0)
All.MainFrame_3.ClipsDescendants = false
All.MainFrame_3.BorderSizePixel = 0

All.UICorner_11.Name = "UICorner"
All.UICorner_11.CornerRadius = UDim.new(0, 8)

All.ScrollingFrame.Name = "ScrollingFrame"
All.ScrollingFrame.ZIndex = 1
All.ScrollingFrame.Position = UDim2.new(0.0163265299, 0, 0.0310880821, 0)
All.ScrollingFrame.Size = UDim2.new(0.971428573, 0, 0.958549201, 0)
All.ScrollingFrame.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.ScrollingFrame.BackgroundTransparency = 1
All.ScrollingFrame.Visible = true
All.ScrollingFrame.AnchorPoint = Vector2.new(0, 0)
All.ScrollingFrame.ClipsDescendants = true
All.ScrollingFrame.CanvasSize = UDim2.new(0, 0, 2, 0)
All.ScrollingFrame.ScrollBarThickness = 8
All.ScrollingFrame.ScrollingEnabled = true
All.ScrollingFrame.BorderSizePixel = 0

All.ESP.Name = "ESP"
All.ESP.ZIndex = 1
All.ESP.Position = UDim2.new(0, 0, -0.000112039437, 0)
All.ESP.Size = UDim2.new(0, 111, 0, 50)
All.ESP.BackgroundColor3 = Color3.fromRGB(40,43,46)
All.ESP.BackgroundTransparency = 0
All.ESP.Text = "ESP"
All.ESP.TextScaled = false
All.ESP.TextSize = 36
All.ESP.Font = Enum.Font.Highway
All.ESP.TextColor3 = Color3.fromRGB(31,34,38)
All.ESP.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.ESP.TextStrokeTransparency = 1
All.ESP.TextWrapped = true
All.ESP.TextXAlignment = Enum.TextXAlignment.Center
All.ESP.TextYAlignment = Enum.TextYAlignment.Center
All.ESP.TextTransparency = 0
All.ESP.Visible = true
All.ESP.AnchorPoint = Vector2.new(0, 0)
All.ESP.ClipsDescendants = false

All.UICorner_12.Name = "UICorner"
All.UICorner_12.CornerRadius = UDim.new(0, 8)

All.UIListLayout.Name = "UIListLayout"
All.UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
All.UIListLayout.Padding = UDim.new(0, 5)
All.UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Left
All.UIListLayout.VerticalAlignment = Enum.VerticalAlignment.Top
All.UIListLayout.FillDirection = Enum.FillDirection.Horizontal

All.FLY.Name = "FLY"
All.FLY.ZIndex = 1
All.FLY.Position = UDim2.new(0, 0, -0.000112039437, 0)
All.FLY.Size = UDim2.new(0, 111, 0, 50)
All.FLY.BackgroundColor3 = Color3.fromRGB(40,43,46)
All.FLY.BackgroundTransparency = 0
All.FLY.Text = "FLY"
All.FLY.TextScaled = false
All.FLY.TextSize = 36
All.FLY.Font = Enum.Font.Highway
All.FLY.TextColor3 = Color3.fromRGB(31,34,38)
All.FLY.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.FLY.TextStrokeTransparency = 1
All.FLY.TextWrapped = true
All.FLY.TextXAlignment = Enum.TextXAlignment.Center
All.FLY.TextYAlignment = Enum.TextYAlignment.Center
All.FLY.TextTransparency = 0
All.FLY.Visible = true
All.FLY.AnchorPoint = Vector2.new(0, 0)
All.FLY.ClipsDescendants = false

All.UICorner_13.Name = "UICorner"
All.UICorner_13.CornerRadius = UDim.new(0, 8)

All.SERVER.Name = "SERVER"
All.SERVER.ZIndex = 1
All.SERVER.Position = UDim2.new(0, 0, -0.000112039437, 0)
All.SERVER.Size = UDim2.new(0, 111, 0, 50)
All.SERVER.BackgroundColor3 = Color3.fromRGB(40,43,46)
All.SERVER.BackgroundTransparency = 0
All.SERVER.Text = "SERVER"
All.SERVER.TextScaled = false
All.SERVER.TextSize = 36
All.SERVER.Font = Enum.Font.Highway
All.SERVER.TextColor3 = Color3.fromRGB(31,34,38)
All.SERVER.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.SERVER.TextStrokeTransparency = 1
All.SERVER.TextWrapped = true
All.SERVER.TextXAlignment = Enum.TextXAlignment.Center
All.SERVER.TextYAlignment = Enum.TextYAlignment.Center
All.SERVER.TextTransparency = 0
All.SERVER.Visible = true
All.SERVER.AnchorPoint = Vector2.new(0, 0)
All.SERVER.ClipsDescendants = false

All.UICorner_14.Name = "UICorner"
All.UICorner_14.CornerRadius = UDim.new(0, 8)

All.NOCLIP.Name = "NOCLIP"
All.NOCLIP.ZIndex = 1
All.NOCLIP.Position = UDim2.new(0, 0, -0.000112039437, 0)
All.NOCLIP.Size = UDim2.new(0, 111, 0, 50)
All.NOCLIP.BackgroundColor3 = Color3.fromRGB(40,43,46)
All.NOCLIP.BackgroundTransparency = 0
All.NOCLIP.Text = "NOCLIP"
All.NOCLIP.TextScaled = false
All.NOCLIP.TextSize = 36
All.NOCLIP.Font = Enum.Font.Highway
All.NOCLIP.TextColor3 = Color3.fromRGB(31,34,38)
All.NOCLIP.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.NOCLIP.TextStrokeTransparency = 1
All.NOCLIP.TextWrapped = true
All.NOCLIP.TextXAlignment = Enum.TextXAlignment.Center
All.NOCLIP.TextYAlignment = Enum.TextYAlignment.Center
All.NOCLIP.TextTransparency = 0
All.NOCLIP.Visible = true
All.NOCLIP.AnchorPoint = Vector2.new(0, 0)
All.NOCLIP.ClipsDescendants = false

All.UICorner_15.Name = "UICorner"
All.UICorner_15.CornerRadius = UDim.new(0, 8)

All.WALKSPEED.Name = "WALKSPEED"
All.WALKSPEED.ZIndex = 1
All.WALKSPEED.Position = UDim2.new(0, 0, -0.000112039437, 0)
All.WALKSPEED.Size = UDim2.new(0, 111, 0, 50)
All.WALKSPEED.BackgroundColor3 = Color3.fromRGB(40,43,46)
All.WALKSPEED.BackgroundTransparency = 0
All.WALKSPEED.Text = "WALKSPEED"
All.WALKSPEED.TextScaled = false
All.WALKSPEED.TextSize = 23
All.WALKSPEED.Font = Enum.Font.Highway
All.WALKSPEED.TextColor3 = Color3.fromRGB(31,34,38)
All.WALKSPEED.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.WALKSPEED.TextStrokeTransparency = 1
All.WALKSPEED.TextWrapped = true
All.WALKSPEED.TextXAlignment = Enum.TextXAlignment.Center
All.WALKSPEED.TextYAlignment = Enum.TextYAlignment.Center
All.WALKSPEED.TextTransparency = 0
All.WALKSPEED.Visible = true
All.WALKSPEED.AnchorPoint = Vector2.new(0, 0)
All.WALKSPEED.ClipsDescendants = false

All.UICorner_16.Name = "UICorner"
All.UICorner_16.CornerRadius = UDim.new(0, 8)

All.JUMPHEIGHT.Name = "JUMPHEIGHT"
All.JUMPHEIGHT.ZIndex = 1
All.JUMPHEIGHT.Position = UDim2.new(0, 0, -0.000112039437, 0)
All.JUMPHEIGHT.Size = UDim2.new(0, 111, 0, 50)
All.JUMPHEIGHT.BackgroundColor3 = Color3.fromRGB(40,43,46)
All.JUMPHEIGHT.BackgroundTransparency = 0
All.JUMPHEIGHT.Text = "JUMPHEIGHT"
All.JUMPHEIGHT.TextScaled = false
All.JUMPHEIGHT.TextSize = 23
All.JUMPHEIGHT.Font = Enum.Font.Highway
All.JUMPHEIGHT.TextColor3 = Color3.fromRGB(31,34,38)
All.JUMPHEIGHT.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.JUMPHEIGHT.TextStrokeTransparency = 1
All.JUMPHEIGHT.TextWrapped = true
All.JUMPHEIGHT.TextXAlignment = Enum.TextXAlignment.Center
All.JUMPHEIGHT.TextYAlignment = Enum.TextYAlignment.Center
All.JUMPHEIGHT.TextTransparency = 0
All.JUMPHEIGHT.Visible = true
All.JUMPHEIGHT.AnchorPoint = Vector2.new(0, 0)
All.JUMPHEIGHT.ClipsDescendants = false

All.UICorner_17.Name = "UICorner"
All.UICorner_17.CornerRadius = UDim.new(0, 8)

All.TOOL.Name = "TOOL"
All.TOOL.ZIndex = 1
All.TOOL.Position = UDim2.new(0, 0, -0.000112039437, 0)
All.TOOL.Size = UDim2.new(0, 111, 0, 50)
All.TOOL.BackgroundColor3 = Color3.fromRGB(40,43,46)
All.TOOL.BackgroundTransparency = 0
All.TOOL.Text = "TOOL"
All.TOOL.TextScaled = false
All.TOOL.TextSize = 36
All.TOOL.Font = Enum.Font.Highway
All.TOOL.TextColor3 = Color3.fromRGB(31,34,38)
All.TOOL.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.TOOL.TextStrokeTransparency = 1
All.TOOL.TextWrapped = true
All.TOOL.TextXAlignment = Enum.TextXAlignment.Center
All.TOOL.TextYAlignment = Enum.TextYAlignment.Center
All.TOOL.TextTransparency = 0
All.TOOL.Visible = true
All.TOOL.AnchorPoint = Vector2.new(0, 0)
All.TOOL.ClipsDescendants = false

All.UICorner_18.Name = "UICorner"
All.UICorner_18.CornerRadius = UDim.new(0, 8)

All.Noclip_SpeedGUI.Name = "Noclip_SpeedGUI"
All.Noclip_SpeedGUI.ResetOnSpawn = false
All.Noclip_SpeedGUI.IgnoreGuiInset = true
All.Noclip_SpeedGUI.DisplayOrder = 0

All.Dragger_4.Name = "Dragger"
All.Dragger_4.ZIndex = 1
All.Dragger_4.Position = UDim2.new(0.294513255, 0, 0.137446374, 0)
All.Dragger_4.Size = UDim2.new(0.323998362, 0, 0.0558748394, 0)
All.Dragger_4.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.Dragger_4.BackgroundTransparency = 1
All.Dragger_4.Visible = false
All.Dragger_4.AnchorPoint = Vector2.new(0, 0)
All.Dragger_4.ClipsDescendants = false
All.Dragger_4.BorderSizePixel = 0
All.Dragger_4.Draggable = true


All.TransMainFrame_4.Name = "TransMainFrame"
All.TransMainFrame_4.ZIndex = 0
All.TransMainFrame_4.Position = UDim2.new(0.000111095535, 0, -0.00602852972, 0)
All.TransMainFrame_4.Size = UDim2.new(1, 0, 4.19999981, 0)
All.TransMainFrame_4.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TransMainFrame_4.BackgroundTransparency = 0.30000001192092896
All.TransMainFrame_4.Visible = true
All.TransMainFrame_4.AnchorPoint = Vector2.new(0, 0)
All.TransMainFrame_4.ClipsDescendants = false
All.TransMainFrame_4.BorderSizePixel = 0

All.UICorner_19.Name = "UICorner"
All.UICorner_19.CornerRadius = UDim.new(0, 8)

All.MainFrame_4.Name = "MainFrame"
All.MainFrame_4.ZIndex = 1
All.MainFrame_4.Position = UDim2.new(0.00653942581, 0, 0.27871412, 0)
All.MainFrame_4.Size = UDim2.new(0.984227121, 0, 0.700680256, 0)
All.MainFrame_4.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.MainFrame_4.BackgroundTransparency = 0
All.MainFrame_4.Visible = true
All.MainFrame_4.AnchorPoint = Vector2.new(0, 0)
All.MainFrame_4.ClipsDescendants = false
All.MainFrame_4.BorderSizePixel = 0

All.UICorner_20.Name = "UICorner"
All.UICorner_20.CornerRadius = UDim.new(0, 8)

All.TextBox_3.Name = "TextBox"
All.TextBox_3.ZIndex = 1
All.TextBox_3.Position = UDim2.new(0.179487184, 0, 0.261682242, 0)
All.TextBox_3.Size = UDim2.new(0.641025662, 0, 0.485436887, 0)
All.TextBox_3.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextBox_3.BackgroundTransparency = 0
All.TextBox_3.Text = "100"
All.TextBox_3.TextScaled = true
All.TextBox_3.TextSize = 14
All.TextBox_3.Font = Enum.Font.Highway
All.TextBox_3.TextColor3 = Color3.fromRGB(138,138,138)
All.TextBox_3.TextStrokeColor3 = Color3.fromRGB(22,24,26)
All.TextBox_3.TextStrokeTransparency = 1
All.TextBox_3.TextWrapped = true
All.TextBox_3.TextXAlignment = Enum.TextXAlignment.Center
All.TextBox_3.TextYAlignment = Enum.TextYAlignment.Center
All.TextBox_3.TextTransparency = 0
All.TextBox_3.ClearTextOnFocus = false
All.TextBox_3.MultiLine = false
All.TextBox_3.Visible = true
All.TextBox_3.AnchorPoint = Vector2.new(0, 0)
All.TextBox_3.ClipsDescendants = false

All.UICorner_21.Name = "UICorner"
All.UICorner_21.CornerRadius = UDim.new(0, 8)

All.TitleFrame_4.Name = "TitleFrame"
All.TitleFrame_4.ZIndex = 1
All.TitleFrame_4.Position = UDim2.new(0.00653923349, 0, 0.0119033083, 0)
All.TitleFrame_4.Size = UDim2.new(0.984227121, 0, 0.238095239, 0)
All.TitleFrame_4.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TitleFrame_4.BackgroundTransparency = 0
All.TitleFrame_4.Visible = true
All.TitleFrame_4.AnchorPoint = Vector2.new(0, 0)
All.TitleFrame_4.ClipsDescendants = false
All.TitleFrame_4.BorderSizePixel = 0

All.UICorner_22.Name = "UICorner"
All.UICorner_22.CornerRadius = UDim.new(0, 8)

All.TextLabel_4.Name = "TextLabel"
All.TextLabel_4.ZIndex = 1
All.TextLabel_4.Position = UDim2.new(0.0279824678, 0, -0.0712120757, 0)
All.TextLabel_4.Size = UDim2.new(0.458333343, 0, 0.971428573, 0)
All.TextLabel_4.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextLabel_4.BackgroundTransparency = 1
All.TextLabel_4.Text = "Noclip - Speed"
All.TextLabel_4.TextScaled = true
All.TextLabel_4.TextSize = 14
All.TextLabel_4.Font = Enum.Font.Highway
All.TextLabel_4.TextColor3 = Color3.fromRGB(40,43,46)
All.TextLabel_4.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.TextLabel_4.TextStrokeTransparency = 1
All.TextLabel_4.TextWrapped = true
All.TextLabel_4.TextXAlignment = Enum.TextXAlignment.Left
All.TextLabel_4.TextYAlignment = Enum.TextYAlignment.Center
All.TextLabel_4.TextTransparency = 0
All.TextLabel_4.Visible = true
All.TextLabel_4.AnchorPoint = Vector2.new(0, 0)
All.TextLabel_4.ClipsDescendants = false

All.Walk_SpeedGUI.Name = "Walk_SpeedGUI"
All.Walk_SpeedGUI.ResetOnSpawn = false
All.Walk_SpeedGUI.IgnoreGuiInset = true
All.Walk_SpeedGUI.DisplayOrder = 0

All.Dragger_5.Name = "Dragger"
All.Dragger_5.ZIndex = 1
All.Dragger_5.Position = UDim2.new(0.294513255, 0, 0.137446374, 0)
All.Dragger_5.Size = UDim2.new(0.323998362, 0, 0.0558748394, 0)
All.Dragger_5.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.Dragger_5.BackgroundTransparency = 1
All.Dragger_5.Visible = false
All.Dragger_5.AnchorPoint = Vector2.new(0, 0)
All.Dragger_5.ClipsDescendants = false
All.Dragger_5.BorderSizePixel = 0
All.Dragger_5.Draggable = true


All.TransMainFrame_5.Name = "TransMainFrame"
All.TransMainFrame_5.ZIndex = 0
All.TransMainFrame_5.Position = UDim2.new(0.000111095535, 0, -0.00602852972, 0)
All.TransMainFrame_5.Size = UDim2.new(1, 0, 4.19999981, 0)
All.TransMainFrame_5.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TransMainFrame_5.BackgroundTransparency = 0.30000001192092896
All.TransMainFrame_5.Visible = true
All.TransMainFrame_5.AnchorPoint = Vector2.new(0, 0)
All.TransMainFrame_5.ClipsDescendants = false
All.TransMainFrame_5.BorderSizePixel = 0

All.UICorner_23.Name = "UICorner"
All.UICorner_23.CornerRadius = UDim.new(0, 8)

All.MainFrame_5.Name = "MainFrame"
All.MainFrame_5.ZIndex = 1
All.MainFrame_5.Position = UDim2.new(0.00653942581, 0, 0.27871412, 0)
All.MainFrame_5.Size = UDim2.new(0.984227121, 0, 0.700680256, 0)
All.MainFrame_5.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.MainFrame_5.BackgroundTransparency = 0
All.MainFrame_5.Visible = true
All.MainFrame_5.AnchorPoint = Vector2.new(0, 0)
All.MainFrame_5.ClipsDescendants = false
All.MainFrame_5.BorderSizePixel = 0

All.UICorner_24.Name = "UICorner"
All.UICorner_24.CornerRadius = UDim.new(0, 8)

All.TextBox_4.Name = "TextBox"
All.TextBox_4.ZIndex = 1
All.TextBox_4.Position = UDim2.new(0.179487184, 0, 0.261682242, 0)
All.TextBox_4.Size = UDim2.new(0.641025662, 0, 0.485436887, 0)
All.TextBox_4.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextBox_4.BackgroundTransparency = 0
All.TextBox_4.Text = "16"
All.TextBox_4.TextScaled = true
All.TextBox_4.TextSize = 14
All.TextBox_4.Font = Enum.Font.Highway
All.TextBox_4.TextColor3 = Color3.fromRGB(138,138,138)
All.TextBox_4.TextStrokeColor3 = Color3.fromRGB(22,24,26)
All.TextBox_4.TextStrokeTransparency = 1
All.TextBox_4.TextWrapped = true
All.TextBox_4.TextXAlignment = Enum.TextXAlignment.Center
All.TextBox_4.TextYAlignment = Enum.TextYAlignment.Center
All.TextBox_4.TextTransparency = 0
All.TextBox_4.ClearTextOnFocus = false
All.TextBox_4.MultiLine = false
All.TextBox_4.Visible = true
All.TextBox_4.AnchorPoint = Vector2.new(0, 0)
All.TextBox_4.ClipsDescendants = false

All.UICorner_25.Name = "UICorner"
All.UICorner_25.CornerRadius = UDim.new(0, 8)

All.TitleFrame_5.Name = "TitleFrame"
All.TitleFrame_5.ZIndex = 1
All.TitleFrame_5.Position = UDim2.new(0.00653923349, 0, 0.0119033083, 0)
All.TitleFrame_5.Size = UDim2.new(0.984227121, 0, 0.238095239, 0)
All.TitleFrame_5.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TitleFrame_5.BackgroundTransparency = 0
All.TitleFrame_5.Visible = true
All.TitleFrame_5.AnchorPoint = Vector2.new(0, 0)
All.TitleFrame_5.ClipsDescendants = false
All.TitleFrame_5.BorderSizePixel = 0

All.UICorner_26.Name = "UICorner"
All.UICorner_26.CornerRadius = UDim.new(0, 8)

All.TextLabel_5.Name = "TextLabel"
All.TextLabel_5.ZIndex = 1
All.TextLabel_5.Position = UDim2.new(0.0279824678, 0, -0.0712120757, 0)
All.TextLabel_5.Size = UDim2.new(0.458333343, 0, 0.971428573, 0)
All.TextLabel_5.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextLabel_5.BackgroundTransparency = 1
All.TextLabel_5.Text = "WalkSpeed"
All.TextLabel_5.TextScaled = true
All.TextLabel_5.TextSize = 14
All.TextLabel_5.Font = Enum.Font.Highway
All.TextLabel_5.TextColor3 = Color3.fromRGB(40,43,46)
All.TextLabel_5.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.TextLabel_5.TextStrokeTransparency = 1
All.TextLabel_5.TextWrapped = true
All.TextLabel_5.TextXAlignment = Enum.TextXAlignment.Left
All.TextLabel_5.TextYAlignment = Enum.TextYAlignment.Center
All.TextLabel_5.TextTransparency = 0
All.TextLabel_5.Visible = true
All.TextLabel_5.AnchorPoint = Vector2.new(0, 0)
All.TextLabel_5.ClipsDescendants = false

All.ToolGUI.Name = "ToolGUI"
All.ToolGUI.ResetOnSpawn = false
All.ToolGUI.IgnoreGuiInset = true
All.ToolGUI.DisplayOrder = 0

All.Dragger_6.Name = "Dragger"
All.Dragger_6.ZIndex = 1
All.Dragger_6.Position = UDim2.new(0.294513255, 0, 0.137446374, 0)
All.Dragger_6.Size = UDim2.new(0.323998362, 0, 0.0558748394, 0)
All.Dragger_6.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.Dragger_6.BackgroundTransparency = 1
All.Dragger_6.Visible = false
All.Dragger_6.AnchorPoint = Vector2.new(0, 0)
All.Dragger_6.ClipsDescendants = false
All.Dragger_6.BorderSizePixel = 0
All.Dragger_7.Draggable = true


All.TransMainFrame_6.Name = "TransMainFrame"
All.TransMainFrame_6.ZIndex = 0
All.TransMainFrame_6.Position = UDim2.new(0.000111095535, 0, -0.00602852972, 0)
All.TransMainFrame_6.Size = UDim2.new(1, 0, 4.19999981, 0)
All.TransMainFrame_6.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TransMainFrame_6.BackgroundTransparency = 0.30000001192092896
All.TransMainFrame_6.Visible = true
All.TransMainFrame_6.AnchorPoint = Vector2.new(0, 0)
All.TransMainFrame_6.ClipsDescendants = false
All.TransMainFrame_6.BorderSizePixel = 0

All.UICorner_27.Name = "UICorner"
All.UICorner_27.CornerRadius = UDim.new(0, 8)

All.MainFrame_6.Name = "MainFrame"
All.MainFrame_6.ZIndex = 1
All.MainFrame_6.Position = UDim2.new(0.00653942581, 0, 0.27871412, 0)
All.MainFrame_6.Size = UDim2.new(0.984227121, 0, 0.700680256, 0)
All.MainFrame_6.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.MainFrame_6.BackgroundTransparency = 0
All.MainFrame_6.Visible = true
All.MainFrame_6.AnchorPoint = Vector2.new(0, 0)
All.MainFrame_6.ClipsDescendants = false
All.MainFrame_6.BorderSizePixel = 0

All.UICorner_28.Name = "UICorner"
All.UICorner_28.CornerRadius = UDim.new(0, 8)

All.TextBox_5.Name = "TextBox"
All.TextBox_5.ZIndex = 1
All.TextBox_5.Position = UDim2.new(0.179487184, 0, 0.261682242, 0)
All.TextBox_5.Size = UDim2.new(0.641025662, 0, 0.485436887, 0)
All.TextBox_5.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextBox_5.BackgroundTransparency = 0
All.TextBox_5.Text = "100"
All.TextBox_5.TextScaled = true
All.TextBox_5.TextSize = 14
All.TextBox_5.Font = Enum.Font.Highway
All.TextBox_5.TextColor3 = Color3.fromRGB(138,138,138)
All.TextBox_5.TextStrokeColor3 = Color3.fromRGB(22,24,26)
All.TextBox_5.TextStrokeTransparency = 1
All.TextBox_5.TextWrapped = true
All.TextBox_5.TextXAlignment = Enum.TextXAlignment.Center
All.TextBox_5.TextYAlignment = Enum.TextYAlignment.Center
All.TextBox_5.TextTransparency = 0
All.TextBox_5.ClearTextOnFocus = false
All.TextBox_5.MultiLine = false
All.TextBox_5.Visible = true
All.TextBox_5.AnchorPoint = Vector2.new(0, 0)
All.TextBox_5.ClipsDescendants = false

All.UICorner_29.Name = "UICorner"
All.UICorner_29.CornerRadius = UDim.new(0, 8)

All.TitleFrame_6.Name = "TitleFrame"
All.TitleFrame_6.ZIndex = 1
All.TitleFrame_6.Position = UDim2.new(0.00653923349, 0, 0.0119033083, 0)
All.TitleFrame_6.Size = UDim2.new(0.984227121, 0, 0.238095239, 0)
All.TitleFrame_6.BackgroundColor3 = Color3.fromRGB(50,50,50)
All.TitleFrame_6.BackgroundTransparency = 0
All.TitleFrame_6.Visible = true
All.TitleFrame_6.AnchorPoint = Vector2.new(0, 0)
All.TitleFrame_6.ClipsDescendants = false
All.TitleFrame_6.BorderSizePixel = 0

All.UICorner_30.Name = "UICorner"
All.UICorner_30.CornerRadius = UDim.new(0, 8)

All.TextLabel_6.Name = "TextLabel"
All.TextLabel_6.ZIndex = 1
All.TextLabel_6.Position = UDim2.new(0.0279824678, 0, -0.0712120757, 0)
All.TextLabel_6.Size = UDim2.new(0.458333343, 0, 0.971428573, 0)
All.TextLabel_6.BackgroundColor3 = Color3.fromRGB(255,255,255)
All.TextLabel_6.BackgroundTransparency = 1
All.TextLabel_6.Text = "TOOL"
All.TextLabel_6.TextScaled = true
All.TextLabel_6.TextSize = 14
All.TextLabel_6.Font = Enum.Font.Highway
All.TextLabel_6.TextColor3 = Color3.fromRGB(40,43,46)
All.TextLabel_6.TextStrokeColor3 = Color3.fromRGB(0,0,0)
All.TextLabel_6.TextStrokeTransparency = 1
All.TextLabel_6.TextWrapped = true
All.TextLabel_6.TextXAlignment = Enum.TextXAlignment.Left
All.TextLabel_6.TextYAlignment = Enum.TextYAlignment.Center
All.TextLabel_6.TextTransparency = 0
All.TextLabel_6.Visible = true
All.TextLabel_6.AnchorPoint = Vector2.new(0, 0)
All.TextLabel_6.ClipsDescendants = false
